Review
Xacor/gophermart pull request #1
Opened 2023-08-27 11:34 UTC by Xacor

2023-08-29 13:59 UTC, Xacor commented
Поначалу хотел сделать все красиво, но потом нагрузили по основной работе и писал просто чтоб заработало. Знаю, что хорошо бы было написать автотесты хотя бы на основную логику, постараюсь сделать во время доработок.

2023-08-30 21:01 UTC, valentinsoe requested changes
Спасибо за работу!

В целом несмотря на мои комментарии все очень даже хорошо. Аккуратно написано, логически понятно. Отлично что код четко(за исключением 1 замечания:) разделен на слои.
Хорошо, что клиент к внешнему сервису отдельная сущность и не производит "лишних" действий.

Чего не хватает?
1) местами транзакций
2) многопоточности при запросах во внешнюю систему. Если даже все ответы будут приходить моментально, то каждый отдельный http запрос может быть не очень быстрым.
3) Обработки кода 429 от внешнего сервиса(хотя под это даже заведена специальная ошибка, которая не используется)

2023-08-30 21:01 UTC, valentinsoe commented on internal/app/migrate.go
Я бы этот файл перенес в пакет с БД все-таки, кажется там он уместнее.

2023-08-30 21:01 UTC, valentinsoe commented on internal/controller/http/api/authentication.go
> +	if err := json.Unmarshal(buf.Bytes(), &user); err != nil {
Можно в целом сразу делать json.Unmarshal(r.Body). Читать через промежуточный буффер большого смысла нет.

2023-08-30 21:01 UTC, valentinsoe commented on internal/controller/http/api/authentication.go
> +	token, err := ar.a.Authenticate(r.Context(), user)
Аутентифицировать пользователя сразу после регистрации - лишняя операция. Можно сразу генерировать токен.

2023-08-30 21:01 UTC, valentinsoe commented on internal/controller/http/api/balance.go
> +	userID := r.Context().Value(jwt.UserIDKey).(int)
Рекомендую сделать отдельную функцию, чтобы не копировать эту строку в почти каждый хендлер.

2023-08-30 21:01 UTC, valentinsoe commented on internal/controller/http/api/balance.go
> +		Current:   converter.IntToFloat(balance.Current),
Хорошо, что приведение типа происходит прямо в хендлере. А не где-то на уровнях "глубже".

2023-08-30 21:01 UTC, valentinsoe commented on internal/controller/http/api/withdrawals.go
> +	if goluhn.Validate(withdraw.Order) != nil {
Непринципиальное занудство. Если эту проверку делать, то можно делать до создания сущности.
Принципиальное занудство. В целом этой проверке место скорее на уровне бизнес-логики(usecase) как это сделано для создания заказа

2023-08-30 21:01 UTC, valentinsoe commented on internal/controller/usecase/authentication.go
> +	hash, err := bcrypt.GenerateFromPassword([]byte(user.Password), 10)
Лучше 10 вынести в константу, чтобы это не было magic number, а имело имя:)

2023-08-30 21:01 UTC, valentinsoe commented on internal/controller/usecase/orders.go
> +	if err == nil {
Если произошла ошибка отличная от "нет таких строк", то это тоже стоит обработать, а не пытаться создать заказ.

2023-08-30 21:01 UTC, valentinsoe commented on internal/controller/usecase/orders.go
> +	return o.orderRepo.Create(ctx, order)
Операции создания и проверки находятся в разных транзакциях. Поэтому отправив одноврменно два запроса с одинаковым заказом - кто-то получит ошибку 500 вместо 200 или 409.

2023-08-30 21:01 UTC, valentinsoe commented on internal/app/app.go
> +		l.Info("shutting down gracefully", zap.String("signal", s.String()))
Фоновая горутина с запросами во внешний сервис не будет "gracefully" остановлена при таком сценарии.

2023-08-30 21:01 UTC, valentinsoe commented on internal/controller/usecase/orders.go
> +	for _, order := range orders {
Получать статусы однопоточно, с учетом ретраев и таймаутов настроенных для  resty клиента - слишком медленно. Пропускная способность такой системы будет очень низкой.

2023-08-30 21:01 UTC, valentinsoe commented on internal/controller/usecase/webapi/accruals.go
> +		return nil, errors.New("to many requests")
Этот статус стоит не просто игнорировать, а переставать делать запросы некоторое время

2023-08-30 21:01 UTC, valentinsoe commented on internal/controller/usecase/webapi/accruals.go
> +func (a *AccrualsAPI) AccrualToOrder(accrual *AccrualResponse, order *entity.Order) {
Этой функции место скорее в пакете с бизнес-логикой. Клиент внешнего сервиса должен возвращать данные как получил, а уже какой-нибудь адаптер на уровень выше, должен их конвертировать.

2023-09-02 17:49 UTC, Xacor commented on internal/controller/http/api/authentication.go
> +	if err := json.Unmarshal(buf.Bytes(), &user); err != nil {
json.Unmarshall принимает []byte, а r.Body возвращает интерфейс ReaderCloser, поэтому все равно придется каким-либо способом считывать Body.

2023-09-07 05:19 UTC, valentinsoe approved these changes
Спасибо за работу! В целом все классно
Написал пару комментариев(исправлять не требуется).
И еще на 429 от внешнего сервиса стоит реагировать чем-то большим, чем надпись об этом в логе.

2023-09-07 05:19 UTC, valentinsoe commented on internal/controller/http/api/authentication.go
> +	if err := json.Unmarshal(buf.Bytes(), &user); err != nil {
json.Decode  можно использовать для потокового чтения.

2023-09-07 05:19 UTC, valentinsoe commented on internal/controller/usecase/orders.go
> +	tx, err := o.orderRepo.Begin(ctx)
Не призываю это менять, но есть более аккуратные способы вынести транзакции на уровень usecase, так чтобы не usecase не был зависим от пакетов sql.
Например так:
https://www.kaznacheev.me/posts/en/clean-transactions-in-hexagon/

2023-09-07 05:51 UTC, merged